name: Scratch for Arduino UNO Q
description: Control the UNO Q board using Scratch blocks
ports:
  - 7000
bricks:
  - arduino:web_ui
  - arduino:object_detection
  - arduino:image_classification
     variables:
        EI_CLASSIFICATION_MODEL: /home/arduino/.arduino-bricks/ei-models/tm-ok-stop.eim
icon: 🐱
