version: "3"
vars:
  SCRATCH_EDITOR_VERSION: v12.0.1
  DPRINT_VERSION: 0.48.0

tasks:
  install:
    cmds:
      - curl -fsSL https://dprint.dev/install.sh | sh -s {{ .DPRINT_VERSION }}
      - mkdir -p .bin && cp $HOME/.dprint/bin/dprint .bin/dprint # workaround for local install

  fmt:
    desc: Run format
    cmds:
      - ${PWD}/.bin/dprint fmt

  fmt:check:
    desc: Check format
    cmds:
      - ${PWD}/.bin/dprint check

  scratch:init:
    cmds:
      - rm -rf scratch-editor
      - git clone --depth 1 --branch {{ .SCRATCH_EDITOR_VERSION }}  https://github.com/scratchfoundation/scratch-editor.git
      - cd scratch-editor && npm install
      - cd scratch-editor && npm run build
      - task scratch:patch

  scratch:patch:
    cmds:
      - cd scratch-editor/packages/scratch-gui && node ../../../scratch-arduino-extensions/scripts/patch-gui.js

  scratch:local:start:
    dir: scratch-editor
    cmds:
      - npm start --workspace @scratch/scratch-gui

  app:build:
    desc: "Copy app files (python, assets, app.yaml) to a build directory"
    cmds:
      - rm -rf build/scratch-arduino-app/
      - mkdir -p build/scratch-arduino-app
      - cp ./app.yaml build/scratch-arduino-app/app.yaml
      - cp -r ./sketch build/scratch-arduino-app/sketch
      - cp -r ./python build/scratch-arduino-app/python
      - cp -r ./certs build/scratch-arduino-app/certs
      - task scratch:build
      - mkdir -p build/scratch-arduino-app/assets
      - cp scratch-editor/packages/scratch-gui/build/index.html build/scratch-arduino-app/assets/index.html
      - cp scratch-editor/packages/scratch-gui/build/gui.js build/scratch-arduino-app/assets/gui.js
      - mkdir -p build/scratch-arduino-app/assets/static
      - cp -r scratch-editor/packages/scratch-gui/build/static/blocks-media  build/scratch-arduino-app/assets/static/blocks-media

  scratch:build:
    desc: "Build Scratch GUI files"
    dir: scratch-editor/packages/scratch-gui
    cmds:
      - npm run build:dev --workspace @scratch/scratch-gui

  board:app:upload:
    desc: "Upload zip file to Arduino board, unzip and deploy to /home/arduino/ArduinoApps"
    cmds:
      - task app:zip
      - |
          ZIP_FILE=$(ls -t build/scratch-arduino-app-*.zip 2>/dev/null | head -n1)
          if [ -z "$ZIP_FILE" ]; then
            echo "No zip file found. Run 'task app:zip' first."
            exit 1
          fi
          adb push "$ZIP_FILE" /tmp/
          ZIP_BASENAME=$(basename "$ZIP_FILE")
          adb shell "cd /tmp && unzip -o $ZIP_BASENAME && mkdir -p /home/arduino/ArduinoApps && rm -rf /home/arduino/ArduinoApps/scratch-arduino-app && mv scratch-arduino-app /home/arduino/ArduinoApps/ && rm $ZIP_BASENAME"
          echo "App deployed to /home/arduino/ArduinoApps/scratch-arduino-app"

  app:zip:
    desc: "Create a zip file with version (defaults to git commit hash)"
    vars:
      APP_VERSION:
        sh: echo "${APP_VERSION:-$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')}"
    cmds:
      - |
          if [ ! -d "build/scratch-arduino-app" ]; then
            echo "Build folder does not exist. Run 'task app:build' first."
            exit 1
          fi
      - echo "Creating zip with version {{.APP_VERSION}}"
      - cd build && zip -r scratch-arduino-app-{{.APP_VERSION}}.zip scratch-arduino-app && cd ..

  watch:
    desc: "wath cfile changes for both python and sketch, and upload the changes to the board and restart"
    deps:
      - python:watch
      - sketch:watch

  python:watch:
    desc: "Watch Python folder for changes and auto-upload/restart"
    silent: true
    cmds:
      - |
          while true; do
            echo "🐍 Waiting for changes in python folder..."
            inotifywait -r -e modify,create,delete,move python/ 2>/dev/null || {
              echo "inotifywait failed, retrying..."
              sleep 2
              continue
            }

            sleep 1 # Waiting 1 second for file writes to complete..."
            echo "🐍  Change detected: uploading and restarting service..."
            task python:upload-and-restart || {
              echo "Upload/restart failed, continuing to watch..."
              continue
            }

          done

  python:upload-and-restart:
    desc: "Upload Python files and restart container"
    silent: true
    cmds:
      - |
          adb push ./python/ /home/arduino/ArduinoApps/scratch-arduino-app/

          CONTAINER_ID=$(adb shell "docker ps -q --filter 'ancestor=ghcr.io/arduino/app-bricks/python-apps-base:0.5.0'")
          if [ -n "$CONTAINER_ID" ]; then
            RESTART_START=$(date +%s)
            adb shell "docker restart $CONTAINER_ID"
            RESTART_END=$(date +%s)
            echo "🐍 Container restarted in $((RESTART_END - RESTART_START))s"
          else
            echo "[warning] No running container found with image ghcr.io/arduino/app-bricks/python-apps-base"
          fi

  sketch:watch:
    desc: "Watch sketch folder for changes and auto-compile/upload"
    silent: true
    cmds:
      - |
          while true; do
            echo "♾️  Waiting for changes in sketch folder..."
            inotifywait -r -e modify,create,delete sketch/ --include '\.(ino|cpp|h|c)$' 2>/dev/null || {
              echo "inotifywait failed, retrying..."
              sleep 2
              continue
            }

            sleep 1   # Waiting 1 second for file writes to complete
            echo "♾️  Change detected: compiling and uploading..."
            task sketch:compile-and-upload|| {
              echo "Compile/upload failed, continuing to watch..."
              continue
            }
            echo
          done

  sketch:compile-and-upload:
    desc: "Compile and upload Arduino sketch"
    silent: true
    cmds:
      - |
          C_START=$(date +%s)
          arduino-cli compile  --build-path .cache -b arduino:zephyr:unoq sketch/
          C_END=$(date +%s)

          U_START=$(date +%s)
          arduino-cli upload -p /dev/ttyACM0 -b arduino:zephyr:unoq:flash_mode=ram --input-dir .cache  sketch/
          U_END=$(date +%s)
          echo "♾️  Compiled in $((C_END - C_START))s, Uploaded in $((U_END - U_START))s"
      # even if not necessary: the sketch folder is sync into the board to have the updated version
      - adb push ./sketch/ /home/arduino/ArduinoApps/scratch-arduino-app/

  sketch:monitor:
    desc: "Open serial monitor for Arduino debugging"
    silent: true
    cmds:
      - echo " ♾️  Opening serial monitor (Press Ctrl+C to exit)..."
      - arduino-cli monitor -p /dev/ttyACM0

  python:monitor:
    desc: "Watch sketch folder for changes and auto-compile/upload"
    cmds:
      - |
          echo "🐍 Python container logs"
          while true; do
           CONTAINER_ID=$(adb shell "docker ps -q --filter 'ancestor=ghcr.io/arduino/app-bricks/python-apps-base:0.5.0'")
           if [ -n "$CONTAINER_ID" ]; then
             adb shell "docker logs -f $CONTAINER_ID"
           else
             echo "[warning] No running container found with image ghcr.io/arduino/app-bricks/python-apps-base"
           fi
           done
